services: 
  db:
    image: postgres
    container_name: db
    restart: always  #container reinicia se morrer
    ports:
      - 5433:5432
    env_file:
      - ./back-end/.env
    volumes:
      - pg:/var/lib/postgresql/data #tudo que estiver em data salvar em pg "tipo um pen driver"
  
  back_end_app:
    container_name: back_end_app
    build: ./back-end  #busca o DockerFile
    ports:
      - 4000:4000
    depends_on:
      - db        #Só sobe de o postgres estiver funcionando
    env_file:
      - ./back-end/.env
  
  react_ngcash_app:
    container_name: react_ngcash_app
    build: ./front-end  #onde fica o dockerfile
    depends_on:
      - db
      - back_end_app
    volumes:
      - build_react:/var/www/html
    env_file:
      - ./front-end/.env

  nginx_ngcash_app:
    container_name: nginx_ngcash_app
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - react_ngcash_app
      
volumes:
  pg:
  build_react: 